image: node:10.16.0-slim

before_script:
  - echo ':before_script'
  - cat /etc/os-release
  - npm --version
  - node --version
  - npm install
  - echo 'end :before_script'

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 day

e2e:
  stage: test
  script:
    - echo 'Starting Angular development Server in the background...'
    - npm run start&
    - chmod +x ./gitlab-pipeline/install-browsers.sh
    - bash -x gitlab-pipeline/install-browsers.sh
    - npm run webdriver-manager-update
    - npm run protractor-chrome-headless
    - npm run protractor-firefox-headless
  artifacts:
    paths:
      - tmp/
    expire_in: 1 day
